version: "3"

services:
  vgx-scanner:
    build: .
    volumes:
      # Mount the target codebase to scan
      - ${SCAN_TARGET:-./}:/scan
      # Mount persistent context directory
      - vgx-context:/root/.vgx
    environment:
      # Pass OpenAI API key from host if available
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Pass VibePenTester API key from host if available
      - VIBE_API_KEY=${VIBE_API_KEY:-}
      - VIBE_ENABLED=${VIBE_ENABLED:-false}
      - VIBE_SERVER_URL=${VIBE_SERVER_URL:-http://localhost:5050}
    command: ${SCAN_CMD:-scan-changes}

volumes:
  vgx-context:
    # Named volume for persistent context storage
